config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#index"
   get "contact", to: "pages#contact"
   get "restaurants", to: "restaurants#index"
   get "restaurants/new", to: "restaurants#new"
   get "restaurants/:id/edit", to: "restaurants#edit", as: :edit
   get "restaurants/:id", to: "restaurants#show", as: :restaurant
   patch "restaurants/:id", to: "restaurants#update"
   post "restaurants", to: "restaurants#create"

   delete "restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
    @members = ["thanh", "dimitri", "germain", "damien", "julien"]

    if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new # Needed to instantiate the form_with
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    # No need for app/views/restaurants/create.html.erb
    redirect_to restaurant_path(@restaurant)
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App-</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>ici contact</h1>

<form action="/contact" method="get">
  <input    type="text" 
            value="<%= params[:member] %>" 
            name="member" 
            placeholder="Who r u loop king for :-) ?">
  <input type="submit">
</form>

<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

<%= link_to "vers index", root_path %>

<%= link_to "vers restaurants", restaurants_path %>

app/views/pages/index.html.erb
<h1>ici index</h1>

<%= link_to "vers contact", contact_path %>
<%= link_to "vers restaurants", restaurants_path %>

app/views/restaurants/edit.html.erb
<h1>EDITER RESTAU</h1>
<br>
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "vers NEW_restaurants", restaurants_new_path %>
<br>
<%= link_to "vers restaurants", restaurants_path %>
<br>

app/views/restaurants/index.html.erb
<h1>RESTAU</h1>
<br>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>
<hr>

<footer>
  <%= link_to "vers NEW_restaurants", restaurants_new_path %>
<br>
<%= link_to "vers restaurants", restaurants_path %>
<br>
  </footer>

app/views/restaurants/new.html.erb
<h1>NEW RESTAU</h1>
<br>
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "vers restaurants", restaurants_path %>
<br>

app/views/restaurants/show.html.erb
<title> Ahhhh </title>
<h1>SHOW</h1>
<br>
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.rating %></p>

<label for="fuel">Rating level:</label>

<meter id="fuel" min="0" max="10" low="3" high="6" optimum="80" value="<%= @restaurant.rating %>">at 50/100</meter>

<hr>
<%= link_to "Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<br>
<%= link_to "vers NEW_restaurants", restaurants_new_path %>
<br>
<%= link_to "vers restaurants", restaurants_path %>
<br>
<%= link_to "vers édition", edit_path %>